### ISSUE TITLE
Ability to create new customers

### ISSUE THREAD

**Issue by KennethOyolla** [visitbasis/visitbasis-issues#11]
We currently have operatives creating new dummy customers when they have not been allocated stores. is it possible to make this an admin functionality i.e. the admin can turn on or off the ability of a mobile user to create new customers. in the absence of this mobil operators are creating dummy customers which is causing a big lad to the platform especially when you want to run reports

**Comment by visitbasis** [comment]
Please use New Location function on mobile app.
