### ISSUE TITLE
Report Generation

### ISSUE THREAD

**Issue by KennethOyolla** [visitbasis/visitbasis-issues#12]
When creating reports in the the report builder format there is the option filter for division. is it possible to make it such that after you enter the division the tasks templates that show up are only fur that division?
Currently use is that after filtering for division you still see all the task templates which are not tagged or differentiated for different accounts. as a result it is near impossible to elect the right task template especially if different accounts have the same task e.g. out of stock

**Comment by visitbasis** [comment]
The report builder is replaced by new Reports. One can filter tasks by divisions easily there.
