### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by KennethOyolla** [visitbasis/visitbasis-issues#14]
Assuming the mobile user always uses Visitbasis on a mobile device, is it possible to create an option to create a geofence round a location meaning the mobile user cannot fill data if there are outside of say 100m of the store? My client says Coca Cola has such a system for the ir field automation solution and would like to see this implemented on Vistbasis if possible

I have shared with client that there is GPS tracking for all tasks for the mobile user but this remains a sticking point for client

**Comment by visitbasis** [comment]
we could have a switch in the Office app so that mobile user will not be able to start a visit if GPS is not confirmed to the POS location <150 miters

**Comment by visitbasis** [comment]
Since version 2.5.3 we are now forcing users to enable GPS for VisitBasis App

**Comment by KennethOyolla** [comment]
Fantastic. Good progress on Visitbasis!
