### ISSUE TITLE
Post codes

### ISSUE THREAD

**Issue by KennethOyolla** [visitbasis/visitbasis-issues#18]
Most parts of developing and emerging markets do not have postcodes and some roads are not marked. The alternative to postcodes is to input nearest town and have these accepted. At present only large towns are recognised whilst google maps is granular enough with details of smaller towns. Can the location be modified so that when you input a small town it is recognised and a location can be locked. Later when the merchandiser visits the store they can capture the exact store location which can then be modified in the system

**Comment by KennethOyolla** [comment]
any update/imptovements on this?

**Comment by visitbasis-ru** [comment]
Hi Kenneth,

Yes, all the above should be working as expected. You can save any location
in the office and later mobile agents can use online tool to update the
address while on the go.

1) http://www.visitbasis.com/online
2) Click on:
"See my territory and edit Customer information"
3) user will see:
https://visitbasis1.appspot.com/territory

On Android users can jump to http://www.visitbasis.com/online from Settings
screen "VisitBasis Online"

Best regards,

Paul.

On Thu, Jan 21, 2016 at 7:25 AM, KennethOyolla notifications@github.com
wrote:

> any update/imptovements on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/visitbasis/visitbasis-issues/issues/18#issuecomment-173556123
> .

## 

_About VisitBasis_
+1 954 505 2059 <%2B1%20954%20505-2059>
http://www.visitbasis.com
https://tawk.to/visitbasis

VisitBasis App - mobile data collection for field merchandising, retail
audits, field marketing and field sales.

**Comment by KennethOyolla** [comment]
Thanks. This solves the issue
