### ISSUE TITLE
Pricelist assigning

### ISSUE THREAD

**Issue by melvinlazeron** [visitbasis/visitbasis-issues#19]
Dear VisitBasis,

I have a suggestion regarding pricelist allocation.

When I make a pricelist i have to allocate it to a customer/location. this is pretty much work if you have over 1500+ stores.

Wouldnt it be easier if you can attach a pricelist to a REP.

So if i make an order at a customer, i can choose between the diffrent pricelists.

So when there is a new customer/location i dont have to assign him a pricelist, and updating is also much easier.

With kind regards,

Melvin Lazeron

**Comment by melvinlazeron** [comment]
Dear VisitBasis,
I have discussed this matters with John @ the support chat.
A reply here is not necessary, however I would love to be updated if there will be taken care of this matters.

With kind regargds,

Melvin Lazeron

**Comment by visitbasis** [comment]
We are going to add Price List/Location in bulk export/import feature for that.
