### ISSUE TITLE
Customer Info/Task Update

### ISSUE THREAD

**Issue by KeijiTsuchiya** [visitbasis/visitbasis-issues#2]
We would like mobile users to update/edit customer information/tasks whenever necessary 

Once mobile users input customer information or task information that we set, they cannot edit or update anything on that specific customer. For example, mobile user goes to customer A and A is closed. However, there is some information that they can input for customer A (address, phone number, notes etc.), so they put that data. On the next day, they revisit A to collect more data. However, at this point, they cannot put or update any information on customer A. Obviously, this is a big issue for us because mobile users cannot get all the necessary information in one visit and they need to visit multiple times for one customer to finalize customer information and tasks.

**Comment by visitbasis** [comment]
You should separate the requirements into two different ones.
1. Ability to update customer data, e.g. Customer name, address, contact info
2. Changes to tasks in the past. 

Regarding task editing. You can only edit task on the day when it is planned. You can edit task many times during the day when task is scheduled. You cannot modify the task in the future or past. This is as designed. If you need to collect data for the same task the best practice is to add a new task with same title and complete it. VisitBasis is not CRM system but a data collection system.

Regarding the ability to change customer profile data by field reps. Most of our clients do not want that feature as it easily can corrupt the customer database leading to duplication or invalid data. The best practice is create a task call it "Customer Info Update" so that field rep can use that to initiate customer update. The office users then will extract the data from the task and apply changes to the customer. This way the changes can be first validated and approved by manager.

**Comment by KeijiTsuchiya** [comment]
1. So, is it impossible to edit task in the future? This does not make any sense to me. If VisitBasis is a data collection system, why do you assume we can collect all data at once or in a day? How can we change the task if any of the item in the task change in the future because nothing is permanent?
   This is very basic setting we expect to do by using the system. 
   Anyways, how do you suggest us to move forward so that we can edit the customer data in the future or it's simple impossible?
2. We would like to update the customer profile data because that is why we hired mobile user to update those information. If we need to create a new task, doesn't it same as 1? I thought you just explained that we cannot change the task in the past or the future? 

....By the way, I just noticed that I can input task for one customer multiple times now. After completing tasks for customer on Day 1, I can still select customer A and complete the task on Day2. Have you changed anything or did I miss something?

**Comment by visitbasis** [comment]
Hi Keiji,

Please be aware that you are communicating via github issue tracking
system. Other users of our system might see what you are writing here, so
keep it short and professional.
1. The task can be scheduled for the future dates. If you change your mind
   you can always delete and re-schedule new tasks for a future date.
   Think about Task as a survey. You can schedule a survey for today for a
   particular customer visit. You collect required data and submit the survey
   to the office application. The survey should be executed on the day it was
   scheduled. Once the survey is submitted it should not be amended in any.
   This is how all the online forms and survey data collection systems work.
   If we allow for you to change the survey submitted in the past your reports
   would be invalid.

Again, editing customer data and task related issue are totally separate
subjects. So please do not mix them.

2.

> > The case for other clients does not matter to me.

 Ideas, suggestions and requests from ALL our clients matter to us. If you
have a feature request we would implement it only if we think that it will
benefit to most of our clients.

> > I thought you just explained that we cannot change the task in the past
> > or the future?

This is how it can work. Let's say you have a visit to customer A and field
rep wants to amend the customer info. The field rep has two options:

a) Write a visit note and tell the office user to amend the customer
profile. You can use Simple query to extract all visit notes very easily.
b) Field rep can add Customer Amend Task to a visit as unplanned and fill
it in. Office user can then use the task collected info and amend the
customer details. You will need to create a simple task template in the
office for that. Do you know how to do any of this? If not ask us for a
demo.

We undestand this might not be the most convenient way to amend the
customer profile. We shall be thinking on how to improve this in the future
versions.

Please book a meeting with us here if you would like to discuss this
offline:
http://meetme.so/visitbasis

Thank you.
VisitBasis Support

_About VisitBasis_
+1 954 505 2059 <%2B1%20954%20505-2059>
http://www.visitbasis.com
https://tawk.to/visitbasis

VisitBasis App - mobile data collection for field merchandising, retail
audits, field marketing and field sales.

**Comment by visitbasis** [comment]
1) Our dev team will look into how to update Customer info using online form:
"Ability to update customer data, e.g. Customer name, address, contact info"

2) We reject the idea of "allowing changes to the tasks that were submitted in previous day" as it breaks our existing stable requirement.

**Comment by KeijiTsuchiya** [comment]
1) Thank you. I understand your system is not built this way but as I explained before, we are using the system to update thousands of customer information based on the mobile users' visits, so we would like to have that function.

2) Again, same as before, we assign mobile users some tasks that are not necessarily completed in a day, thus such function will be very helpful but understand the limitation of VisitBasis.

**Comment by visitbasis** [comment]
We have implemented a pages where field rep can
- View all assigned customers and the map  
- Edit Customer information

To access the page use this URL:

https://visitbasis1.appspot.com/territory
or from mobile app

www.visitbasis.com/online

Enjoy!
