### ISSUE TITLE
Making a order on the phone APP

### ISSUE THREAD

**Issue by melvinlazeron** [visitbasis/visitbasis-issues#20]
Dear VisitBasis,

If i check my customer database on the Iphone app if I press Locations: i cant make a task, to order items.

i can only do this when i plan a visit in the schedule.

could this be updated also? so i can just go to my customer database on the app and make a order.

With kind regards,

Melvin Lazeron

**Comment by melvinlazeron** [comment]
Dear VisitBasis,
I have discussed this matters with John @ the support chat.
A reply here is not necessary, however I would love to be updated if there will be taken care of this matters.

With kind regargds,

Melvin Lazeron

**Comment by visitbasis** [comment]
Hi Melvin,

Sorry for the delay with the reply.

This is how we can implement this feature. From Location list user can create an Order. A new visit and Order task will be automatically created if needed in the current date.

Will that work?

Anna

**Comment by melvinlazeron** [comment]
Hi Anna,

I know this works like that, but I get orders on the daily from customers which I dont visit.

So it would be handy if I can go to my customer list and make a task there, instead of making a visit on the same day which i am not going to visit the customer.

With kind regards,

Melvin Lazeron

**Comment by visitbasis** [comment]
well, you will get to the Order task form immediately from customer (a. k.
a. location) profile screen. But it will be wrapped by a visit. As
everything should be contained in visit for reporting purposes etc. We are
unlikely to change that data model in near future.

On Thu, Jan 28, 2016 at 8:38 AM, melvinlazeron notifications@github.com
wrote:

> Hi Anna,
> 
> I know this works like that, but I get orders on the daily from customers
> which I dont visit.
> 
> So it would be handy if I can go to my customer list and make a task
> there, instead of making a visit on the same day which i am not going to
> visit the customer.
> 
> With kind regards,
> 
> Melvin Lazeron
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/visitbasis/visitbasis-issues/issues/20#issuecomment-176188875
> .

## 

_About VisitBasis_
+1 954 505 2059 <%2B1%20954%20505-2059>
http://www.visitbasis.com
https://tawk.to/visitbasis

VisitBasis App - mobile data collection for field merchandising, retail
audits, field marketing and field sales.

**Comment by melvinlazeron** [comment]
Hi Anna,

Yes, it was a suggestion which would be really handy for our organization.

And maybe something to update in the future.

Thank you for your answer.

With kind regards,

Melvin Lazeron
Sales Assistant

Dyson Benelux
Keizersgracht 209
1016DT  Amsterdam
The Netherlands
Tel. (06) 20 41 80 07
Email: melvin.lazeron@dyson.commailto:melvin.lazeron@dyson.com

N.B. Het staat de wederverkoper vrij om zelf de verkoopprijzen vast te stellen.
[Description: cid:image004.jpg@01D107F1.578CE7E0]
[Description: cid:image003.jpg@01CEC5AB.5BCAA610]http://www.facebook.com/dyson

[Description: cid:image005.jpg@01CEC5AB.5BCAA610]http://www.twitter.com/askdyson

[Description: cid:image007.jpg@01CEC5AB.5BCAA610]http://www.linkedin.com/company/dyson
