### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by KeijiTsuchiya** [visitbasis/visitbasis-issues#3]
We would like functions to map multiple customers on the map itself for mobile users.

Mobile users can see the location of each visit on map but only individually and not as a group. This again is an issue because we will assign hundreds of customers for each mobile user to visit and they will select which customer to visit every day based only on address. However, as you can imagine, it is difficult to choose the most efficient group based only on address information. Optimization program is based only on distance, not the travel time using trains etc. that is how mobile users travel in Japan, so not that helpful especially when mobile users choose which customers to visit for the day from hundreds of total customer base.

**Comment by visitbasis** [comment]
Hi Keiji,

Thanks for the suggestion. We shall put this feature request on our dev team to-do list. This should be implemented within next 30 days.

Thank you.

**Comment by KeijiTsuchiya** [comment]
Thank you!!
