### ISSUE TITLE
User Photos

### ISSUE THREAD

**Issue by KennethOyolla** [visitbasis/visitbasis-issues#8]
User Photos – Since most of the organisations have a large number of merchandisers, there is a suggestion to have a provision of pictures for the users on the user pane. This will augment the ease of identifying users especially for the office staff when using the Desktop version and interacting with staff in the field

**Comment by KennethOyolla** [comment]
Looking forward to this being closed

**Comment by visitbasis** [comment]
We have integrated VisitiBasis with gravatar.com. So please ask all users to create a profile on  gravatar.com with a photo. VisitBasis Users tab will show the photo of the selected user. When you click on the user name you will be taken to the user profile page.
